name: build our image

on:
  push:
    branches:
      - master
    paths:
      - Dockerfile
  schedule:
    # * is a special character in YAML so you have to quote this string
    # run every sunday as long as no cache or webhook in configured
    - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: docker buildx build --push
             --tag werty1st/espruinowebide:latest
             --platform linux/amd64,linux/arm/v7,linux/arm64 .

      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_LOGIN_PASSWORD }}
        with:
          destination_container_repo: werty1st/espruinowebide
          provider: dockerhub
          short_description: ''
          readme_file: 'README.md'
        
